
export const PhoneBrand = [
    { value: 'iPhone', label: 'iPhone' },
    { value: 'Samsung', label: 'Samsung' },
    { value: 'Xiaomi', label: 'Xiaomi' },
    { value: 'Acer', label: 'Acer' },
    { value: 'Alcatel', label: 'Alcatel' },
    { value: 'Archos', label: 'Archos' },
    { value: 'ASUS', label: 'ASUS' },
    { value: 'BlackBerry', label: 'BlackBerry' },
    { value: 'Google', label: 'Google' },
    { value: 'Hisense', label: 'Hisense' },
    { value: 'Honor', label: 'Honor' },
    { value: 'HTC', label: 'HTC' },
    { value: 'Huawei', label: 'Huawei' },
    { value: 'Infinix', label: 'Infinix' },
    { value: 'Innjoo', label: 'Innjoo' },
    { value: 'Lava', label: 'Lava' },
    { value: 'Lenovo', label: 'Lenovo' },
    { value: 'LG', label: 'LG' },
    { value: 'Meizu', label: 'Meizu' },
    { value: 'Microsoft', label: 'Microsoft' },
    { value: 'Motorola', label: 'Motorola' },
    { value: 'Nokia', label: 'Nokia' },
    { value: 'One Plus', label: 'One Plus' },
    { value: 'OPPO', label: 'OPPO' },
    { value: 'Realme', label: 'Realme' },
    { value: 'Sony', label: 'Sony' },
    { value: 'Tecno', label: 'Tecno' },
    { value: 'Vivo', label: 'Vivo' },
    { value: 'Xtouch', label: 'Xtouch' },
    { value: 'ZTE', label: 'ZTE' },
]