export const CarBrand = [
    { id: 1, name: 'Audi' },
    { id: 2, name: 'Aston Martin' },
    { id: 3, name: 'Alfa Romeo' },
    { id: 4, name: 'BYD' },
    { id: 5, name: 'Buick' },
    { id: 6, name: 'Bugatti' },
    { id: 7, name: 'Brilliance' },
    { id: 8, name: 'BMW' },
    { id: 9, name: 'Bestune' },
    { id: 10, name: 'Bentley' },
    { id: 11, name: 'Baic' },
    { id: 12, name: 'Citroen' },
    { id: 13, name: 'Chrysler' },
    { id: 14, name: 'Chevrolet' },
    { id: 15, name: 'Chery' },
    { id: 16, name: 'Changhe' },
    { id: 17, name: 'Chana' },
    { id: 18, name: 'Cadillac' },
    { id: 19, name: 'Dodge' },
    { id: 20, name: 'DFSK' },
    { id: 21, name: 'Daihatsu' },
    { id: 22, name: 'Daewoo' },
    { id: 23, name: 'Ford' },
    { id: 24, name: 'Geely' },
    { id: 25, name: 'Fiat' },
    { id: 26, name: 'Ferrari' },
    { id: 27, name: 'Faw' },
    { id: 28, name: 'Great Wall' },
    { id: 29, name: 'GMC' },
    { id: 30, name: 'Hyundai' },
    { id: 31, name: 'Haval' },
    { id: 32, name: 'Honda' },
    { id: 33, name: 'Hummer' },
    { id: 34, name: 'Jetour' },
    { id: 35, name: 'Jeep' },
    { id: 36, name: 'Jaguar' },
    { id: 37, name: 'Jac' },
    { id: 38, name: 'Isuzu' },
    { id: 39, name: 'Infiniti' },
    { id: 40, name: 'Kia' },
    { id: 41, name: 'King Long' },
    { id: 42, name: 'KYC' },
    { id: 43, name: 'Lada' },
    { id: 44, name: 'Lamborghini' },
    { id: 45, name: 'Lancia' },
    { id: 46, name: 'Mercedes-Benz' },
]