export const CarBrand = [
    { value: 'Audi', label: 'Audi' },
    { value: 'Aston Martin', label: 'Aston Martin' },
    { value: 'Alfa Romeo', label: 'Alfa Romeo' },
    { value: 'BYD', label: 'BYD' },
    { value: 'Buick', label: 'Buick' },
    { value: 'Bugatti', label: 'Bugatti' },
    { value: 'Brilliance', label: 'Brilliance' },
    { value: 'BMW', label: 'BMW' },
    { value: 'Bestune', label: 'Bestune' },
    { value: 'Bentley', label: 'Bentley' },
    { value: 'Baic', label: 'Baic' },
    { value: 'Citroen', label: 'Citroen' },
    { value: 'Chrysler', label: 'Chrysler' },
    { value: 'Chevrolet', label: 'Chevrolet' },
    { value: 'Chery', label: 'Chery' },
    { value: 'Changhe', label: 'Changhe' },
    { value: 'Chana', label: 'Chana' },
    { value: 'Cadillac', label: 'Cadillac' },
    { value: 'Dodge', label: 'Dodge' },
    { value: 'DFSK', label: 'DFSK' },
    { value: 'Daihatsu', label: 'Daihatsu' },
    { value: 'Daewoo', label: 'Daewoo' },
    { value: 'Ford', label: 'Ford' },
    { value: 'Geely', label: 'Geely' },
    { value: 'Fiat', label: 'Fiat' },
    { value: 'Ferrari', label: 'Ferrari' },
    { value: 'Faw', label: 'Faw' },
    { value: 'Great Wall', label: 'Great Wall' },
    { value: 'GMC', label: 'GMC' },
    { value: 'Hyundai', label: 'Hyundai' },
    { value: 'Haval', label: 'Haval' },
    { value: 'Honda', label: 'Honda' },
    { value: 'Hummer', label: 'Hummer' },
    { value: 'Jetour', label: 'Jetour' },
    { value: 'Jeep', label: 'Jeep' },
    { value: 'Jaguar', label: 'Jaguar' },
    { value: 'Jac', label: 'Jac' },
    { value: 'Isuzu', label: 'Isuzu' },
    { value: 'Infiniti', label: 'Infiniti' },
    { value: 'Kia', label: 'Kia' },
    { value: 'King Long', label: 'King Long' },
    { value: 'KYC', label: 'KYC' },
    { value: 'Lada', label: 'Lada' },
    { value: 'Lamborghini', label: 'Lamborghini' },
    { value: 'Lancia', label: 'Lancia' },
    { value: 'Mercedes-Benz', label: 'Mercedes-Benz' },
]
// export const CarBrand = [
//     { id: 1, label: 'Audi' },
//     { id: 2, label: 'Aston Martin' },
//     { id: 3, label: 'Alfa Romeo' },
//     { id: 4, label: 'BYD' },
//     { id: 5, label: 'Buick' },
//     { id: 6, label: 'Bugatti' },
//     { id: 7, label: 'Brilliance' },
//     { id: 8, label: 'BMW' },
//     { id: 9, label: 'Bestune' },
//     { id: 10, label: 'Bentley' },
//     { id: 11, label: 'Baic' },
//     { id: 12, label: 'Citroen' },
//     { id: 13, label: 'Chrysler' },
//     { id: 14, label: 'Chevrolet' },
//     { id: 15, label: 'Chery' },
//     { id: 16, label: 'Changhe' },
//     { id: 17, label: 'Chana' },
//     { id: 18, label: 'Cadillac' },
//     { id: 19, label: 'Dodge' },
//     { id: 20, label: 'DFSK' },
//     { id: 21, label: 'Daihatsu' },
//     { id: 22, label: 'Daewoo' },
//     { id: 23, label: 'Ford' },
//     { id: 24, label: 'Geely' },
//     { id: 25, label: 'Fiat' },
//     { id: 26, label: 'Ferrari' },
//     { id: 27, label: 'Faw' },
//     { id: 28, label: 'Great Wall' },
//     { id: 29, label: 'GMC' },
//     { id: 30, label: 'Hyundai' },
//     { id: 31, label: 'Haval' },
//     { id: 32, label: 'Honda' },
//     { id: 33, label: 'Hummer' },
//     { id: 34, label: 'Jetour' },
//     { id: 35, label: 'Jeep' },
//     { id: 36, label: 'Jaguar' },
//     { id: 37, label: 'Jac' },
//     { id: 38, label: 'Isuzu' },
//     { id: 39, label: 'Infiniti' },
//     { id: 40, label: 'Kia' },
//     { id: 41, label: 'King Long' },
//     { id: 42, label: 'KYC' },
//     { id: 43, label: 'Lada' },
//     { id: 44, label: 'Lamborghini' },
//     { id: 45, label: 'Lancia' },
//     { id: 46, label: 'Mercedes-Benz' },
// ]